const marketModel = {
    location: "군자동",
    items: [
        {
            id: 1,
            title: "에어팟 프로",
            location: "군자동",
            timeAgo: "3일 전",
            price: "220,000원",
            image: "./assets/airpod.png",
            image_alt: "airpod",
            comments: 3,
            likes: 11,
            isSold: true,
        },
        {
            id: 2,
            title: "바이레도 블랑쉬 50ml",
            location: "광진구 구의제3동",
            timeAgo: "26초 전",
            price: "4,000원",
            image: "./assets/perfume.png",
            image_alt: "perfume",
            comments: 0,
            likes: 2,
            isSold: true,
        },
        {
            id: 3,
            title: "샌드위치",
            location: "동대문구 휘경동",
            timeAgo: "끝물 59초 전",
            price: "8,000원",
            image: "./assets/sandwich.png",
            image_alt: "sandwich",
            comments: 0,
            likes: 0,
            isSold: true,
        },
        {
            id: 4,
            title: "아이폰 13프로맥스",
            location: "군자동",
            timeAgo: "1일 전",
            price: "1,000,000원",
            image: "./assets/ipone.png",
            image_alt: "ipone",
            comments: 0,
            likes: 0,
            isSold: true,
        },
        {
            id: 5,
            title: "커피머신",
            location: "구리시 교문1동",
            timeAgo: "1초 전",
            price: "100,000원",
            image: "./assets/airpod.png",
            image_alt: "airpod",
            comments: 0,
            likes: 0,
            isSold: false,
        },
        {
            id: 6,
            title: "컴퓨터 구조론",
            location: "서울시 화양동",
            timeAgo: "1분전",
            price: "11,000원",
            image: "./assets/airpod.png",
            image_alt: "airpod",
            comments: 0,
            likes: 0,
            isSold: false,
        },
        {
            id: 7,
            title: "맥북 에어 m1 13인치",
            location: "광주",
            timeAgo: "13분 전",
            price: "600,000원",
            image: "./assets/airpod.png",
            image_alt: "airpod",
            comments: 4,
            likes: 12,
            isSold: true,
        },
    ],
};

export default marketModel;
